version: '3.7'

services:
  zm:
    image: netcasper/zoneminder:latest-ubuntu18.04
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 512000000
    environment:
      TZ: 'America/Los_Angeles'
    deploy:
      replicas: 1
