version: '3.7'

services:
  zm:
    image: netcasper/zoneminder:latest
    volumes:
      - zmdbvol:/var/lib/mysql
      - zmlogvol:/var/log/zm
      - zmevent:/var/cache/zoneminder
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 512000000
    environment:
      TZ: 'America/Los_Angeles'
    ports:
      - 2080:80
    deploy:
      replicas: 1

volumes:
  zmdbvol:
    driver: local
    driver_opts:
      type: "nfs4"
      o: "addr=${ZM_NFS_SERVER},rw"
      device: ":/zm/mysql"
  zmlogvol:
    driver: local
    driver_opts:
      type: "nfs4"
      o: "addr=${ZM_NFS_SERVER},rw"
      device: ":/zm/log"
  zmevent:
    driver: local
    driver_opts:
      type: "nfs4"
      o: "addr=${EVENT_NFS_SERVER},rw"
      device: ":/media/zoneminder"
